# version: '3.3' # version is deprecated

# Define the services/containers to be run
services:

  glassfish:
    image: omnifish/glassfish:7.0.4
    ports:
      - "8080:8080"
      - "8181:8181" # HTTPS listener
      - "4848:4848" # HTTPS admin listener
      - "9009:9009" # Debug port
    restart: always
    #    environment:
    #    JVM_ARGS: ""
    #     - "AS_ADMIN_MASTERPASSWORD=admin" #default password is `changeit`
    volumes:
      - ./deployments:/opt/glassfish7/glassfish/domains/domain1/autodeploy

  wildfly:
    image: quay.io/wildfly/wildfly:28.0.1.Final-jdk17
    ports:
      - "8080:8080"
      - "9990:9990" # admin listener
    restart: always
    command: /opt/jboss/wildfly/bin/standalone.sh  -c, standalone-full.xml -b 0.0.0.0 -bmanagement 0.0.0.0
    #    environment:
    volumes:
      - ./deployments:/opt/jboss/wildfly/standalone/deployments

  openliberty:
    image: icr.io/appcafe/open-liberty:23.0.0.4-full-java17-openj9-ubi
    ports:
      - "9080:9080"
      - "9443:9443" # HTTPS listener
    restart: always
    #    command: configure.sh # use for open-liberty:kernel image.
    #    environment:
    volumes:
      - ./src/main/liberty/config/server.xml:/config/server.xml
      - ./deployments:/config/apps